/***********************************************************************/
/*                                                                     */
/*  FILE        :Climate_Control.c                                     */
/*  DATE        :Mon, Jul 28, 2014                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :23                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/

#include "ref\\interrupts.h"
#include "ref\\utilities.h"

uint8 menu_flag=0;

void main(void)
{
	uint8 i=0;
	system_init();
	
	splash_screen();	
	
	while(1){
		
		if(menu_flag){
			menu_invoke();	
		}
		
		read_sensors();
		error_process();			
		update_display();
		update_devices();

		delay(50000);
		}
}
