/***********************************************************************/
/*                                                                     */
/*  FILE        :cstartdef.h                                           */
/*  DATE        :Mon, Jul 28, 2014                                     */
/*  DESCRIPTION :define the size of stack.                             */
/*  CPU GROUP   :23                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/
#define __STACKSIZE__    0x80        /* Modify this line if you change the stack size. */
#define __ISTACKSIZE__   0x80        /* Modify this line if you change the interrupt stack size. */
#define __HEAPSIZE__     0x0         /* Modify this line if you change the heap size. */
#define __STANDARD_IO__  0 			/* Modify this line if you change the standard I/O using. */
#define __WATCH_DOG__    0 			/* Modify this line if you change the Watchdog timer using. */
